### ISSUE TITLE
bugfix: targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE 

### ISSUE THREAD

**Issue by AbolfaZlRezaEe** [AbolfaZlRezaEe/NMock#44]
## Bug Stacktrace

java.lang.IllegalArgumentException: me.abolfazl.nmock: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
    at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
    at android.app.PendingIntent.getActivity(PendingIntent.java:444)
    at android.app.PendingIntent.getActivity(PendingIntent.java:408)
    at com.google.android.gms.common.GoogleApiAvailabilityLight.getErrorResolutionPendingIntent
    at com.google.android.gms.common.GoogleApiAvailabilityLight.getErrorResolutionPendingIntent
    at com.google.android.gms.common.GoogleApiAvailability.getErrorResolutionPendingIntent
    at com.google.android.gms.common.GoogleApiAvailability.getErrorResolutionPendingIntent
    at com.google.android.gms.common.GoogleApiAvailability.zaa
    at com.google.android.gms.common.api.internal.GoogleApiManager.zac
    at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed
    at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.connect
    at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa
    at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at com.google.android.gms.internal.base.zap.dispatchMessage
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by AbolfaZlRezaEe** [comment]
### for now we disable application for APIs above 30
